name: terraform-destroy-workspace
description: Delete a terraform workspace, destroying all resources
author: Daniel Flook

inputs:
  path:
    description: Path to the terraform configuration
    required: false
    default: .
  workspace:
    description: Name of the terraform workspace
    required: true
  backend_config:
    description: List of backend config values to set, one per line
    required: false
    default: ""
  backend_config_file:
    description: Path to a backend config file
    required: false
    default: ""
  variables:
    description: Variable definitions
    required: false
  var:
    description: Comma separated list of vars to set, e.g. 'foo=bar'
    required: false
    deprecationMessage: Use the variables input instead.
  var_file:
    description: List of var file paths, one per line
    required: false
  parallelism:
    description: Limit the number of concurrent operations
    required: false
    default: "0"

runs:
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:456bfa30fe140388801051677636a73e40368f1b43e13a082eb89e58357db54c
  entrypoint: /entrypoints/destroy-workspace.sh

branding:
  icon: globe
  color: purple
