name: terraform-destroy-workspace
description: Delete a terraform workspace, destroying all resources
author: Daniel Flook

inputs:
  path:
    description: Path to the terraform configuration
    required: true
  workspace:
    description: Name of the terraform workspace
    required: true
  backend_config:
    description: List of backend configs to set, one per line
    required: false
  backend_config_file:
    description: Path to a backend config file
    required: false
  variables:
    description: Variable definitions
    required: false
  var:
    description: Comma separated list of vars to set, e.g. 'foo=bar'
    required: false
    deprecationMessage: Use the variables input instead.
  var_file:
    description: List of var file paths, one per line
    required: false
  parallelism:
    description: Limit the number of concurrent operations
    required: false
    default: 0

runs:
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:c98e0c3326bc4947ef37341e38d2239e6c87f53f6720f8b6ec99d2b86360ec8a
  entrypoint: /entrypoints/destroy-workspace.sh

branding:
  icon: globe
  color: purple
